config/routes.rb
Rails.application.routes.draw do

  root 'appointments#index'
  resources :appointments, only: [:edit, :update]
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  has_one :appointment_visitor
  belongs_to :directory

  accepts_nested_attributes_for :appointment_visitor

  def self.check_in(visitor, params)
    directory = Directory.by_name('Lobby')
    appointment = visitor.appointment
    appointment_params = {directory_id: directory.id, appointment_visitor_attributes: params.merge(checked_in_at: Time.current)}
    appointment.update_attributes(appointment_params) ? appointment : nil
  end

end

app/models/appointment_visitor.rb
class AppointmentVisitor < ActiveRecord::Base

  belongs_to :appointment

  def name
    [firstname, lastname].join(' ')
  end
end

app/models/directory.rb
class Directory < ActiveRecord::Base

  has_many :appointments

  def self.by_name(name)
    find_by(name: name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :find_appointment, except: :index

  def index
    @visitor = AppointmentVisitor.first
  end

  def edit
  end

  # NOTE: This method doesn't look conventional on purpose.
  # The app these bits are taken from has some crazy stuff in it.
  def update
    if @appointment = Appointment.check_in(@visitor, appointment_params)
      redirect_to root_path, notice: 'Checked-in'
    else
      redirect_to root_path, alert: 'Failed check-in'
    end
  end

  private

  def find_appointment
    @visitor = AppointmentVisitor.find(params[:id])
  end

  def appointment_params
    params.require(:appointment_visitor).permit(:appointment_id, :firstname, :lastname, :phone, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/edit.html.erb
<%= form_for(@visitor, url: appointment_path(@visitor)) do |f| %>
  <%= f.hidden_field(:appointment_id) %>
  <p><%= f.text_field(:firstname, placeholder: 'First Name') %></p>
  <p><%= f.text_field(:lastname, placeholder: 'Last Name') %></p>
  <p><%= f.text_field(:phone, placeholder: 'Phone Number') %></p>
  <p><%= f.text_field(:email, placeholder: 'Email') %></p>
  <p><%= f.submit('Check-In') %></p>
<% end %>

app/views/appointments/index.html.erb
<%= link_to('Visitor Check-in', edit_appointment_path(@visitor)) %>

<h2>Appointments</h2>
<div>
  <p>Name: <%= @visitor.name %></p>
  <p>Phone: <%= @visitor.phone %></p>
  <p>Email: <%= @visitor.email %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestingBug</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p><%= notice %></p>
  <p><%= alert %></p>
  <%= yield %>

</body>
</html>